In [53]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.impute import MissingIndicator,SimpleImputer

In [54]:
df=pd.read_csv(r"A:\Work Docs\DATA Set\titanic_train.csv",usecols=['Age','Fare','Survived'])

In [55]:
df.head()

Survived   Age     Fare
0         0  22.0   7.2500
1         1  38.0  71.2833
2         1  26.0   7.9250
3         1  35.0  53.1000
4         0  35.0   8.0500

In [56]:
df.isnull().mean()*100

Survived     0.00000
Age         19.86532
Fare         0.00000
dtype: float64

In [57]:
x=df.drop(columns=['Survived'])
y=df['Survived']

In [58]:
x_train, x_test, y_train, y_test=train_test_split(x,y,test_size=0.2,random_state=2)

In [59]:
x_train.head()

Age     Fare
30   40.0  27.7208
10    4.0  16.7000
873  47.0   9.0000
182   9.0  31.3875
876  20.0   9.8458

In [60]:
si=SimpleImputer()
x_train_trf=si.fit_transform(x_train)
x_test_trf=si.transform(x_test)

In [61]:
x_train_trf

array([[ 40.        ,  27.7208    ],
       [  4.        ,  16.7       ],
       [ 47.        ,   9.        ],
       ...,
       [ 71.        ,  49.5042    ],
       [ 29.78590426, 221.7792    ],
       [ 29.78590426,  25.925     ]])

In [76]:
from sklearn.linear_model import LogisticRegression

clf=LogisticRegression()

clf.fit(x_train_trf,y_train)

y_pred=clf.predict(x_test_trf)

from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)*100

61.452513966480446

# Process 1 (lengthy)
### import Missing class, Make object, Merge the column coming from object to original Data

In [63]:
mi=MissingIndicator()
mi.fit(x_train)

MissingIndicator()

In [64]:
mi.features_

array([0], dtype=int64)

In [65]:
x_train_missing=mi.transform(x_train)
x_test_missing=mi.transform(x_test)
x_train_missing

array([[False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [

In [68]:
x_test_missing

array([[False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [

In [66]:
x_train['Age_NA']=x_train_missing
x_train.sample(5)

Age     Fare  Age_NA
201   NaN  69.5500    True
524   NaN   7.2292    True
276  45.0   7.7500   False
767  30.5   7.7500   False
220  16.0   8.0500   False

In [71]:
x_test['Age_NA']=x_test_missing
x_test.sample(5)

Age    Fare  Age_NA
851  74.0   7.775   False
595  36.0  24.150   False
198   NaN   7.750    True
423  28.0  14.400   False
317  54.0  14.000   False

In [72]:
x_train

Age      Fare  Age_NA
30   40.0   27.7208   False
10    4.0   16.7000   False
873  47.0    9.0000   False
182   9.0   31.3875   False
876  20.0    9.8458   False
..    ...       ...     ...
534  30.0    8.6625   False
584   NaN    8.7125    True
493  71.0   49.5042   False
527   NaN  221.7792    True
168   NaN   25.9250    True

[712 rows x 3 columns]

In [73]:
si=SimpleImputer()

x_train_trf2=si.fit_transform(x_train)
x_test_trf2=si.transform(x_test)

In [75]:
from sklearn.linear_model import LogisticRegression

clf =LogisticRegression()

clf.fit(x_train_trf2,y_train)

y_pred=clf.predict(x_test_trf2)

from sklearn.metrics import accuracy_score

accuracy_score(y_test,y_pred)*100

63.128491620111724

# Precess 2 (Short and Clean)
### Just use-   add_indicator=True

In [81]:
si=SimpleImputer(add_indicator=True)

x_train=si.fit_transform(x_train)
x_test=si.transform(x_test)

In [80]:
from sklearn.linear_model import LogisticRegression

clf =LogisticRegression()

clf.fit(x_train,y_train)

y_pred=clf.predict(x_test)

from sklearn.metrics import accuracy_score

accuracy_score(y_test,y_pred)*100

63.128491620111724