In [72]:
from sklearn.datasets import load_diabetes

import numpy as np
from sklearn.linear_model import LinearRegression
from  sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split

import time

In [73]:
x,y =load_diabetes(return_X_y=True)

In [74]:
print(x.shape)
print(y.shape)

(442, 10)
(442,)


In [75]:
x_train, x_test, y_train, y_test =train_test_split(x, y, test_size=0.2, random_state=2)

In [76]:
reg = LinearRegression()
start=time.time()
reg.fit(x_train, y_train)
end=time.time()
print('the time taken in ', end-start)

the time taken in  0.0029921531677246094


In [77]:
reg.coef_

array([  -9.15865318, -205.45432163,  516.69374454,  340.61999905,
       -895.5520019 ,  561.22067904,  153.89310954,  126.73139688,
        861.12700152,   52.42112238])

In [78]:
reg.intercept_

151.88331005254167

In [79]:
y_pred=reg.predict(x_test)
r2_score(y_test,y_pred)

0.4399338661568968

In [80]:
# Mini Batch Gradient Descent Class
import random 

random.randint

class MBGDRegressor:
    def __init__(self,batch_size,learning_rate=0.01, epochs=100) -> None:
        self.batch_size=batch_size
        self.coef_=None
        self.intercept_=None
        self.lr=learning_rate
        self.epochs=epochs

    def fit(self, x_train, y_train):
        self.intercept_ = 0
        self.coef_ = np.ones(x_train.shape[1])

        for i in range(self.epochs):
           

           for j in range(int(x_train.shape[0]/self.batch_size)):

                idx=random.sample(range(x_train.shape[0]),self.batch_size)

                # vectorization of y
                y_hat=np.dot(x_train[idx], self.coef_) + self.intercept_
                slope_intercept= -2 * np.mean( y_train[idx] - y_hat)
                self.intercept_ = self.intercept_ - self.lr* slope_intercept

                slope_coef =-2 * np.dot((y_train[idx]-y_hat),x_train[idx])
                self.coef_ = self.coef_ - (self.lr * slope_coef)
                
        
        
        print(self.intercept_)
        print(self.coef_)

    def predict(self, x_test):
        return np.dot(x_test, self.coef_)+self.intercept_

In [85]:
mbgd=MBGDRegressor(batch_size=int(x_train.shape[0]/10),learning_rate=0.01,epochs=50)

In [82]:
mbgd.fit(x_train,y_train)

152.07685903097126
[  -3.62326041 -202.75094763  532.44523703  334.95320728  -78.9956678
  -99.87385897 -186.12301293   77.61408243  540.14871771   41.4544633 ]


In [83]:
y_pred=mbgd.predict(x_test)

In [84]:
r2_score(y_test, y_pred)

0.445865100966083

MBGD using SGDRegressor class of scikit learn

In [99]:
from sklearn.linear_model import SGDRegressor

In [100]:
sgd=SGDRegressor(learning_rate='constant',eta0=0.2)

In [102]:
batch_size=35

for i in range(100):
    idx=random.sample(range(x_train.shape[0]), batch_size)
    sgd.partial_fit(x_train[idx],y_train[idx])

In [103]:
sgd.coef_

array([  31.23923508, -131.16026443,  436.25585053,  279.22876158,
        -18.87752324,  -94.10428871, -194.27794181,  115.38821208,
        427.67476933,  119.74819327])

In [104]:
sgd.intercept_

array([162.73296914])

In [105]:
y_pred=sgd.predict(x_test)

In [106]:
r2_score(y_test,y_pred)

0.4324325904880656